language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t saumitrakahate/docker-react -f Dockerfile.dev .

script:  
  - docker run -e CI=true saumitrakahate/docker-react npm run test