FROM node:16-alpine

USER node

RUN mkdir -p /home/node/app
WORKDIR '/app'

COPY --chown=node:node ./package.json ./
RUN sudo npm install -g --unsafe-perm=true --allow-root
COPY --chown=node:node ./ ./

CMD ["npm","run","start"]